server:
  port: 8080

spring:
  application:
    name: meeting-app-be
  datasource:
    url: ${DB_CONNECTION}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    user:
      name: user
      password: user
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: ${RESOURCE_ID}
      principle-attribute: ${PRINCIPLE_ATTRIBUTE}

keycloak:
  admin:
    server-url: https://meet.soict.io/auth
    realm: meeting
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}