name: Deploy to VPS

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Build image
        run: docker build -t o0happycat0o/meeting-app:latest .

      - name: Push image
        run: docker push o0happycat0o/meeting-app:latest

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /home/ubuntu/meeting-app
            sudo docker pull o0happycat0o/meeting-app:latest
            sudo docker-compose down
            sudo docker-compose up -d